name = "sigma-flow-storefront"
compatibility_date = "2026-01-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "sigma-flow-db"
database_id = "48ab2ad5-dcd9-4384-be0b-aa6a71bd22ce"
