import {db,defaults,initialize} from '@/lib/store';
import {checkoutDetailsSchema} from '@/lib/checkout';
const json=(d:unknown,status=200)=>Response.json(d,{status});
export async function GET(){try{await initialize();const d=db();const p=await d.prepare('SELECT * FROM products ORDER BY rowid').all();const s=await d.prepare("SELECT value FROM settings WHERE id='store'").first<{value:string}>();return json({products:p.results,settings:s?JSON.parse(s.value):defaults})}catch(e){console.error('Store read failed');return json({error:'Store is temporarily unavailable.'},503)}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Invalid origin'},403);const raw=await req.text();if(raw.length>20000)return json({error:'Request too large'},413);const b=JSON.parse(raw),d=db();await initialize();
if(b.op==='add'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>100||typeof b.category!=='string'||!b.category.trim()||b.category.length>50||!Number.isSafeInteger(b.price)||b.price<1||b.price>10000000||typeof b.image!=='string'||b.image.length>2000)return json({error:'Check the product details.'},400);if(b.image&&!/^https:\/\//.test(b.image))return json({error:'Use an HTTPS image URL.'},400);const id=crypto.randomUUID();await d.prepare('INSERT INTO products(id,name,category,price,image) VALUES(?,?,?,?,?)').bind(id,b.name.trim(),b.category.trim(),b.price,b.image).run();return json({id})}
if(b.op==='delete'){if(typeof b.id!=='string')return json({error:'Invalid product'},400);await d.prepare('DELETE FROM products WHERE id=?').bind(b.id).run();return json({ok:true})}
if(b.op==='settings'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>30||typeof b.headline!=='string'||!b.headline.trim()||b.headline.length>120||typeof b.description!=='string'||b.description.length>220||!/^#[a-fA-F0-9]{6}$/.test(b.accent))return json({error:'Check your store settings.'},400);await d.prepare("UPDATE settings SET value=? WHERE id='store'").bind(JSON.stringify({name:b.name,headline:b.headline,description:b.description,accent:b.accent})).run();return json({ok:true})}
if(b.op==='checkout'){const details=checkoutDetailsSchema.safeParse(b.details);if(!details.success)return json({error:details.error.issues[0]?.message||'Enter your contact details and shipping address.'},400);if(typeof b.card!=='string'||b.card.replace(/ /g,'')!=='4242424242424242'||typeof b.expiry!=='string'||! /^(0[1-9]|1[0-2])\/[0-9]{2}$/.test(b.expiry))return json({error:'Use the demo card 4242 4242 4242 4242 and a valid expiry.'},400);const [m,y]=b.expiry.split('/').map(Number);if(new Date(2000+y,m,1)<=new Date())return json({error:'Use a future expiry date.'},400);if(!Array.isArray(b.items)||!b.items.length||b.items.length>100)return json({error:'Your bag is empty or too large.'},400);let total=0;const items=[];const ids=new Set();for(const i of b.items){if(typeof i.id!=='string'||!Number.isSafeInteger(i.quantity)||i.quantity<1||i.quantity>99||ids.has(i.id))return json({error:'Invalid quantity.'},400);ids.add(i.id);const p=await d.prepare('SELECT id,name,price FROM products WHERE id=?').bind(i.id).first<{id:string,name:string,price:number}>();if(!p)return json({error:'A product is no longer available. Refresh your bag.'},409);total+=p.price*i.quantity;items.push({...p,quantity:i.quantity})}const id=crypto.randomUUID(),token='demo_'+crypto.randomUUID(),createdAt=new Date().toISOString();await d.prepare('INSERT INTO orders(id,total,items,token,last4,expiry,created,checkout_details) VALUES(?,?,?,?,?,?,?,?)').bind(id,total,JSON.stringify(items),token,'4242',b.expiry,createdAt,JSON.stringify(details.data)).run();const receipt={schemaVersion:1,id,createdAt,mode:'test',status:'saved',currency:'USD',totalCents:total,items,contact:details.data.contact,shipping:details.data.shipping,payment:{status:'not_charged',token,brand:'visa',last4:'4242',expiry:b.expiry}};return json({id,total,status:'practice_complete',receipt})}
return json({error:'Unknown action'},400)
}catch(e){console.error('Store request failed');return json({error:'Could not save. Please try again.'},500)}}
