"use client";
import {useEffect,useState} from 'react';
import {ShoppingBag,Plus,ArrowUpRight,SlidersHorizontal,Minus,Trash2,Check,Package} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast,Toaster} from 'sonner';
type Product={id:string;name:string;category:string;price:number;image:string};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
export default function Home(){
const [products,setProducts]=useState<Product[]>([]),[settings,setSettings]=useState({name:'FORM',headline:'Good things.\nEveryday living.',description:'Considered essentials for the spaces you make your own.',accent:'#c9f45b'}),[cart,setCart]=useState<Record<string,number>>({}),[view,setView]=useState('shop'),[modal,setModal]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[order,setOrder]=useState('');
async function load(){try{const r=await fetch('/api/store');if(!r.ok)throw Error('Store is temporarily unavailable. Please try again.');const d=await r.json() as any;setProducts(d.products);setSettings(d.settings);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
async function action(data:unknown){setBusy(true);try{const r=await fetch('/api/store',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'Please try again.');return d;}catch(e){toast.error((e as Error).message);throw e}finally{setBusy(false)}}
function add(id:string){setCart(c=>({...c,[id]:Math.min(99,(c[id]||0)+1)}));toast.success('Added to your bag')}
useEffect(()=>{const mc=(document as any).modelContext;if(!mc)return;const a=new AbortController();Promise.resolve(mc.registerTool({name:'list_store_products',description:'Read current store products',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw Error("This tool takes an empty object.");return {products}}},{signal:a.signal})).catch(()=>{});return()=>a.abort()},[products]);
const items=products.filter(p=>cart[p.id]),total=items.reduce((n,p)=>n+p.price*cart[p.id],0),count=items.reduce((n,p)=>n+cart[p.id],0);
return <div style={{'--lime':settings.accent} as React.CSSProperties}><Toaster richColors/><div className="announcement">A little less ordinary. A lot more you. <span>THE EVERYDAY COLLECTION</span></div><header><a className="logo" href="/">{settings.name}<span>®</span></a><nav><button className={view==='shop'?'selected':''} onClick={()=>setView('shop')}>Shop</button><button className={view==='studio'?'selected':''} onClick={()=>setView('studio')}><SlidersHorizontal size={15}/> Store studio</button></nav><button className="bag" onClick={()=>setModal('cart')}><ShoppingBag size={19}/> Bag <b>{count}</b></button></header>
<main>{view==='shop'?<><section className="intro"><div><p className="eyebrow">OBJECTS WITH INTENTION / COLLECTION 01</p><h1>{settings.headline}</h1><p className="subtitle">{settings.description}</p></div><div className="intro-note"><span>Made for your<br/>kind of everyday.</span><ArrowUpRight size={40}/></div></section><div className="collection-head"><h2>The everyday edit <span>{products.length.toString().padStart(2,'0')}</span></h2><span>Good design, no excess.</span></div></>:<section className="studio-head"><p className="eyebrow">YOUR STORE, YOUR RULES</p><h1>Store studio.</h1><p className="subtitle">Make it yours. Change the look, curate the collection.</p><div className="actions"><button className="primary" onClick={()=>setModal('product')}><Plus size={17}/> Add product</button><button className="outline" onClick={()=>setModal('settings')}><SlidersHorizontal size={17}/> Customize store</button></div></section>}
{error?<div className="empty">{error}<button onClick={load}>Try again</button></div>:loading?<div className="empty">Loading the collection…</div>:<section className="product-grid">{products.map((p,i)=><article key={p.id}><div className={'product-image tone-'+i%3}>{p.image?<img src={p.image} alt={p.name}/>:<Package size={70}/>}<span className="product-label">{p.category}</span><button aria-label={'Add '+p.name+' to bag'} className="quick-add" onClick={()=>add(p.id)}><Plus size={21}/></button></div><div className="product-info"><div><h3>{p.name}</h3><p>{p.category}</p></div><span>{money(p.price)}</span></div>{view==='studio'&&<button className="delete" disabled={busy} onClick={()=>setModal('delete:'+p.id)}><Trash2 size={14}/> Delete product</button>}</article>)}</section>}{!loading&&!error&&!products.length&&<div className="empty">Your collection starts here. Add a product in Store studio.</div>}
<div className="bottom-note"><span><Check size={16}/> Thoughtfully selected</span><span><Package size={16}/> Made for everyday</span><span>Practice store · No real charges</span></div></main><footer><a className="logo" href="/">{settings.name}<span>®</span></a><p>Less, but better.</p><span>© {new Date().getFullYear()} {settings.name}</span></footer>
<Dialog open={!!modal} onOpenChange={o=>!o&&setModal('')}><DialogContent className="store-dialog"><DialogTitle>{modal==='cart'?'Your bag':modal==='checkout'?'Practice checkout':modal==='product'?'Add a product':modal==='settings'?'Make it yours':modal==='success'?'You’re all set.':'Delete product?'}</DialogTitle><DialogDescription>{modal==='checkout'?'Demo only. Use 4242 4242 4242 4242, a future expiry, and CVV 123. No payment is processed.':modal==='success'?'Your practice order has been saved.':'Your everyday essentials, your way.'}</DialogDescription>
{modal==='cart'&&<>{items.length?items.map(p=><div className="cart-row" key={p.id}><div><strong>{p.name}</strong><p>{money(p.price)}</p></div><div className="quantity"><button aria-label={'Remove one '+p.name} onClick={()=>setCart(c=>({...c,[p.id]:Math.max(0,c[p.id]-1)}))}><Minus size={14}/></button><span>{cart[p.id]}</span><button aria-label={'Add one '+p.name} onClick={()=>add(p.id)}><Plus size={14}/></button></div></div>):<p className="empty">Your bag is waiting for something good.</p>}<div className="total"><span>Total</span><strong>{money(total)}</strong></div><button className="primary" disabled={!items.length} onClick={()=>setModal('checkout')}>Continue to checkout <ArrowUpRight size={18}/></button></>}
{modal==='checkout'&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const d=await action({op:'checkout',items:items.map(p=>({id:p.id,quantity:cart[p.id]})),card:f.get('card'),expiry:f.get('expiry')});setOrder(d.id);setCart({});setModal('success')}catch{}}}><div className="wallets"><button type="button" onClick={()=>toast.info('Apple Pay is currently unavailable')}>Apple Pay <small>Currently unavailable</small></button><button type="button" onClick={()=>toast.info('Google Pay is currently unavailable')}>Google Pay <small>Currently unavailable</small></button></div><label>Demo card number<input name="card" required placeholder="4242 4242 4242 4242" inputMode="numeric" pattern="4242 ?4242 ?4242 ?4242"/></label><div className="two-col"><label>Expiry<input required name="expiry" placeholder="MM/YY" pattern="(0[1-9]|1[0-2])/[0-9]{2}"/></label><label>Demo CVV<input required placeholder="123" inputMode="numeric" pattern="123" type="password" maxLength={3}/></label></div><p className="helper">Only a demo payment token, expiry and last four digits are saved. Card number and CVV are not stored.</p><button className="primary" disabled={busy}> {busy?'Saving…':`Place practice order · ${money(total)}`}</button></form>}
{modal==='success'&&<div className="success"><Check size={48}/><h3>Thanks for stopping by.</h3><p>Order {order.slice(0,8).toUpperCase()}</p><p>No money was charged.</p><button className="primary" onClick={()=>setModal('')}>Back to the collection</button></div>}
{modal==='product'&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await action({op:'add',name:f.get('name'),category:f.get('category'),price:Math.round(Number(f.get('price'))*100),image:f.get('image')});await load();setModal('');toast.success('Product added')}catch{}}}><label>Product name<input name="name" required maxLength={100}/></label><div className="two-col"><label>Price (USD)<input name="price" type="number" min="0.01" max="100000" step="0.01" required/></label><label>Category<input name="category" required maxLength={50} placeholder="Home & living"/></label></div><label>Image URL (optional)<input type="url" name="image" placeholder="https://…"/></label><button disabled={busy} className="primary">{busy?'Saving…':'Add product'}</button></form>}
{modal==='settings'&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await action({op:'settings',...Object.fromEntries(f)});await load();setModal('');toast.success('Store updated')}catch{}}}><label>Store name<input name="name" defaultValue={settings.name} required maxLength={30}/></label><label>Headline<textarea name="headline" defaultValue={settings.headline} required maxLength={120}/></label><label>Description<textarea name="description" defaultValue={settings.description} maxLength={220}/></label><label>Accent color<input type="color" name="accent" defaultValue={settings.accent}/></label><button disabled={busy} className="primary">Save changes</button></form>}
{modal.startsWith('delete:')&&<><p>This removes the product from your storefront.</p><button className="primary" disabled={busy} onClick={async()=>{try{await action({op:'delete',id:modal.split(':')[1]});await load();setModal('')}catch{}}}>Delete product</button><button className="outline" onClick={()=>setModal('')}>Keep product</button></>}
</DialogContent></Dialog></div>}
